name: nightly

on:
  push:
    paths:
      - "**.zig"
      - "build.zig.zon"
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - uses: actions/checkout@v4

      - run: zig fmt --check src/**/*.zig build.zig build.zig.zon
  build-native:
    strategy:
      matrix:
        include:
          - os: macos-latest
            cpu_flag: "-Dcpu=apple_m1"
          - os: windows-latest
            cpu_flag: "-Dcpu=x86_64_v3"
    runs-on: ${{matrix.os}}
    steps:
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4

      - name: prepare-macos
        if: runner.os == 'macOS'
        run: brew install ffmpeg dylibbundler

      - name: build
        run: zig build -Doptimize=ReleaseSafe ${{ matrix.cpu_flag }}

      - name: bundle-dylibs
        if: runner.os == 'macOS'
        run: |
          dylibbundler -cd -b -x zig-out/bin/rota-stabilizer -d zig-out/bin/libs -p @executable_path/libs

          codesign --force --sign - zig-out/bin/libs/*.dylib
          codesign --force --sign - zig-out/bin/rota-stabilizer

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: rota-stabilizer-${{matrix.os}}
          path: zig-out

  build-flatpak:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-25.08
      options: --privileged
    steps:
      - uses: actions/checkout@v4

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: rota-stabilizer.flatpak
          manifest-path: moe.paoda.rota-stabilizer.yml
          cache-key: flatpak-builder-${{ github.sha }}

      - name: Upload Flatpak Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rota-stabilizer-flatpak
          path: rota-stabilizer.flatpak
